# Generated by Django 4.2.1 on 2023-05-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vier_node', '0003_remove_pricing_table_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing_table',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
