# Generated by Django 4.2.1 on 2023-05-31 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vier_node', '0004_pricing_table_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing_table',
            name='create_at',
        ),
        migrations.AddField(
            model_name='pricing_table',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
